services:
  conversational-friends-api:
    image: josephrashidmaalouf/conversational-friends-api:latest
    container_name: conversational-friends-api
    ports:
      - "5000:5000"
    environment:
      OpenAiKey: "your-openai-api-key-here"
    pull_policy: always

  conversational-friends-frontend:
    image: josephrashidmaalouf/conversational-friends-frontend:latest
    container_name: conversational-friends-frontend
    ports:
      - "3000:80"
    environment:
      API_URL: "http://localhost:5000/"
    pull_policy: always
